import type { ShoppingCategory } from '../types'

const WORD_MAP: Record<string, string> = {
  // Frukt & grønt
  eple: 'frukt & grønt', epler: 'frukt & grønt', banan: 'frukt & grønt', bananer: 'frukt & grønt',
  appelsin: 'frukt & grønt', appelsiner: 'frukt & grønt', sitron: 'frukt & grønt', lime: 'frukt & grønt',
  drue: 'frukt & grønt', druer: 'frukt & grønt', jordbær: 'frukt & grønt', blåbær: 'frukt & grønt',
  bringebær: 'frukt & grønt', mango: 'frukt & grønt', ananas: 'frukt & grønt', melon: 'frukt & grønt',
  vannmelon: 'frukt & grønt', avokado: 'frukt & grønt', avokadoer: 'frukt & grønt',
  tomat: 'frukt & grønt', tomater: 'frukt & grønt', cherrytomater: 'frukt & grønt',
  agurk: 'frukt & grønt', paprika: 'frukt & grønt', løk: 'frukt & grønt', rødløk: 'frukt & grønt',
  hvitløk: 'frukt & grønt', gulrot: 'frukt & grønt', gulrøtter: 'frukt & grønt',
  brokkoli: 'frukt & grønt', blomkål: 'frukt & grønt', kål: 'frukt & grønt', rødkål: 'frukt & grønt',
  spinat: 'frukt & grønt', salat: 'frukt & grønt', romanosalat: 'frukt & grønt', isbergsalat: 'frukt & grønt',
  potet: 'frukt & grønt', poteter: 'frukt & grønt', søtpotet: 'frukt & grønt',
  sopp: 'frukt & grønt', sjampinjong: 'frukt & grønt', mais: 'frukt & grønt',
  erter: 'frukt & grønt', squash: 'frukt & grønt', selleri: 'frukt & grønt',
  ingefær: 'frukt & grønt', persille: 'frukt & grønt', basilikum: 'frukt & grønt',
  koriander: 'frukt & grønt', dill: 'frukt & grønt', gressløk: 'frukt & grønt',
  pære: 'frukt & grønt', pærer: 'frukt & grønt', fersken: 'frukt & grønt', kirsebær: 'frukt & grønt',
  plomme: 'frukt & grønt', bønner: 'frukt & grønt', sukkererter: 'frukt & grønt',
  purre: 'frukt & grønt', reddik: 'frukt & grønt', nektarin: 'frukt & grønt',
  asparges: 'frukt & grønt', asperges: 'frukt & grønt',
  bakepotet: 'frukt & grønt', rotgrønnsaker: 'frukt & grønt',
  pak: 'frukt & grønt', pakchoi: 'frukt & grønt',
  frukt: 'frukt & grønt',
  'gul løk': 'frukt & grønt',

  // Meieri
  melk: 'meieri', lettmelk: 'meieri', helmelk: 'meieri', skummetmelk: 'meieri',
  plantemelk: 'meieri', havremelk: 'meieri', mandelmelk: 'meieri', soyamelk: 'meieri',
  smør: 'meieri', margarin: 'meieri', ost: 'meieri', kremost: 'meieri',
  cottage: 'meieri', rømme: 'meieri', crème: 'meieri',
  fløte: 'meieri', matfløte: 'meieri', kremfløte: 'meieri',
  yoghurt: 'meieri', kesam: 'meieri', kvark: 'meieri', skyr: 'meieri',
  egg: 'meieri', brunost: 'meieri', hvitost: 'meieri', norvegia: 'meieri',
  jarlsberg: 'meieri', gouda: 'meieri', brie: 'meieri', camembert: 'meieri',
  parmesanost: 'meieri', mozzarella: 'meieri', fetaost: 'meieri', ricotta: 'meieri',
  cheddar: 'meieri', gruyère: 'meieri', seterrømme: 'meieri',
  meierismør: 'meieri', bremykt: 'meieri', kryddersmør: 'meieri',
  mozz: 'meieri', mozarella: 'meieri',
  skummet: 'meieri', mellomyoghurt: 'meieri', mellommelk: 'meieri', mellom: 'meieri',
  julegrøt: 'meieri',
  'flytende margarin': 'meieri',

  // Kjøtt & fisk
  kylling: 'kjøtt & fisk', kyllingfilet: 'kjøtt & fisk', kyllinglår: 'kjøtt & fisk',
  kyllingvinger: 'kjøtt & fisk', kyllingkjøttdeig: 'kjøtt & fisk',
  svinekjøtt: 'kjøtt & fisk', svinefilet: 'kjøtt & fisk', ribbe: 'kjøtt & fisk',
  svinekotelett: 'kjøtt & fisk', kjøttdeig: 'kjøtt & fisk', karbonadedeig: 'kjøtt & fisk',
  laks: 'kjøtt & fisk', laksfilet: 'kjøtt & fisk', torsk: 'kjøtt & fisk',
  torskfilet: 'kjøtt & fisk', sei: 'kjøtt & fisk', hyse: 'kjøtt & fisk',
  reke: 'kjøtt & fisk', reker: 'kjøtt & fisk', biff: 'kjøtt & fisk',
  entrecôte: 'kjøtt & fisk', ytrefilet: 'kjøtt & fisk', indrefilet: 'kjøtt & fisk',
  pølse: 'kjøtt & fisk', pølser: 'kjøtt & fisk', grillpølser: 'kjøtt & fisk',
  wiener: 'kjøtt & fisk', bacon: 'kjøtt & fisk', makrell: 'kjøtt & fisk',
  tunfisk: 'kjøtt & fisk', lammekjøtt: 'kjøtt & fisk', lammelår: 'kjøtt & fisk',
  lammekotelett: 'kjøtt & fisk', kjøtt: 'kjøtt & fisk', fisk: 'kjøtt & fisk',
  krabbe: 'kjøtt & fisk', hummer: 'kjøtt & fisk', blåskjell: 'kjøtt & fisk',
  ørret: 'kjøtt & fisk', kveite: 'kjøtt & fisk', flyndre: 'kjøtt & fisk',
  svinekoteletter: 'kjøtt & fisk', medisterkaker: 'kjøtt & fisk',
  grillmat: 'kjøtt & fisk', karbonader: 'kjøtt & fisk', storfe: 'kjøtt & fisk',

  // Brød & bakevarer
  loff: 'brød & bakevarer', brød: 'brød & bakevarer', rundstykker: 'brød & bakevarer',
  knekkebrød: 'brød & bakevarer', kavring: 'brød & bakevarer', pitabrød: 'brød & bakevarer',
  bagel: 'brød & bakevarer', croissant: 'brød & bakevarer', kake: 'brød & bakevarer',
  kjeks: 'brød & bakevarer', bolle: 'brød & bakevarer', boller: 'brød & bakevarer',
  baguette: 'brød & bakevarer', lefse: 'brød & bakevarer', tortilla: 'brød & bakevarer',
  wraps: 'brød & bakevarer', focaccia: 'brød & bakevarer', ciabatta: 'brød & bakevarer',
  surdeig: 'brød & bakevarer', grovbrød: 'brød & bakevarer', kneipbrød: 'brød & bakevarer',
  muffins: 'brød & bakevarer', vafler: 'brød & bakevarer', pannekaker: 'brød & bakevarer',
  skorpe: 'brød & bakevarer', flatbrød: 'brød & bakevarer', cracker: 'brød & bakevarer',
  lompe: 'brød & bakevarer', lomper: 'brød & bakevarer',
  pølsebrød: 'brød & bakevarer', polarbrød: 'brød & bakevarer',
  wasa: 'brød & bakevarer', hvitbag: 'brød & bakevarer', møllerhjul: 'brød & bakevarer',

  // Pålegg og tilbehør
  leverpostei: 'pålegg og tilbehør', syltetøy: 'pålegg og tilbehør',
  jordbærsyltetøy: 'pålegg og tilbehør', bringebærsyltetøy: 'pålegg og tilbehør',
  blåbærsyltetøy: 'pålegg og tilbehør', marmelade: 'pålegg og tilbehør',
  peanøttsmør: 'pålegg og tilbehør', nugatti: 'pålegg og tilbehør', nutella: 'pålegg og tilbehør',
  kaviar: 'pålegg og tilbehør', rekesalat: 'pålegg og tilbehør', tunfisksalat: 'pålegg og tilbehør',
  makrelsalat: 'pålegg og tilbehør', fiskesalat: 'pålegg og tilbehør',
  eggesalat: 'pålegg og tilbehør', hummus: 'pålegg og tilbehør', tapenade: 'pålegg og tilbehør',
  pesto: 'pålegg og tilbehør', guacamole: 'pålegg og tilbehør',
  salami: 'pålegg og tilbehør', spekeskinke: 'pålegg og tilbehør',
  mortadella: 'pålegg og tilbehør', kokt: 'pålegg og tilbehør',
  skinke: 'pålegg og tilbehør', roastbiff: 'pålegg og tilbehør',
  serranoskinke: 'pålegg og tilbehør', prosciutto: 'pålegg og tilbehør',
  pålegg: 'pålegg og tilbehør', pepperoni: 'pålegg og tilbehør',
  chorizo: 'pålegg og tilbehør', potetsalat: 'pålegg og tilbehør', berne: 'pålegg og tilbehør',

  // Saus, dressing, krydder
  sennep: 'saus, dressing, krydder', ketchup: 'saus, dressing, krydder',
  majones: 'saus, dressing, krydder', aioli: 'saus, dressing, krydder',
  saus: 'saus, dressing, krydder', buljong: 'saus, dressing, krydder',
  krydder: 'saus, dressing, krydder', kanel: 'saus, dressing, krydder',
  karri: 'saus, dressing, krydder', pepper: 'saus, dressing, krydder',
  salt: 'saus, dressing, krydder', dressing: 'saus, dressing, krydder',
  soyasaus: 'saus, dressing, krydder', worcester: 'saus, dressing, krydder',
  tabasco: 'saus, dressing, krydder', chilisaus: 'saus, dressing, krydder',
  sriracha: 'saus, dressing, krydder', hvitløkssaus: 'saus, dressing, krydder',
  tzatziki: 'saus, dressing, krydder', sambal: 'saus, dressing, krydder',
  paprikapulver: 'saus, dressing, krydder', gurkemeie: 'saus, dressing, krydder',
  oregano: 'saus, dressing, krydder', timian: 'saus, dressing, krydder',
  rosmarin: 'saus, dressing, krydder', laurbær: 'saus, dressing, krydder',
  chili: 'saus, dressing, krydder', cumin: 'saus, dressing, krydder',
  ingefærpulver: 'saus, dressing, krydder', kardemomme: 'saus, dressing, krydder',
  vaniljesukker: 'saus, dressing, krydder', sennepspulver: 'saus, dressing, krydder',
  fiskesaus: 'saus, dressing, krydder', ostesaus: 'saus, dressing, krydder',
  bearnaise: 'saus, dressing, krydder', brun: 'saus, dressing, krydder',
  hvit: 'saus, dressing, krydder', tomatpuré: 'saus, dressing, krydder',
  tomatsaus: 'saus, dressing, krydder', pastasaus: 'saus, dressing, krydder',
  woksaus: 'saus, dressing, krydder', hoisin: 'saus, dressing, krydder',
  hvitvinseddik: 'saus, dressing, krydder', eddik: 'saus, dressing, krydder',
  fahitakrydder: 'saus, dressing, krydder', fahitaskrydder: 'saus, dressing, krydder',
  fajitakrydder: 'saus, dressing, krydder', tacokrydder: 'saus, dressing, krydder',

  // Tørrvarer og hermetikk
  pasta: 'tørrvarer og hermetikk', spaghetti: 'tørrvarer og hermetikk',
  penne: 'tørrvarer og hermetikk', fusilli: 'tørrvarer og hermetikk',
  tagliatelle: 'tørrvarer og hermetikk', lasagne: 'tørrvarer og hermetikk',
  ris: 'tørrvarer og hermetikk', basmatiris: 'tørrvarer og hermetikk',
  jasminris: 'tørrvarer og hermetikk', havregryn: 'tørrvarer og hermetikk',
  mel: 'tørrvarer og hermetikk', hvetemel: 'tørrvarer og hermetikk',
  rugmel: 'tørrvarer og hermetikk', speltmel: 'tørrvarer og hermetikk',
  sukker: 'tørrvarer og hermetikk', melis: 'tørrvarer og hermetikk',
  brunt: 'tørrvarer og hermetikk', olje: 'tørrvarer og hermetikk',
  olivenolje: 'tørrvarer og hermetikk', rapsolje: 'tørrvarer og hermetikk',
  solsikkeolje: 'tørrvarer og hermetikk', hermetikk: 'tørrvarer og hermetikk',
  hermetisert: 'tørrvarer og hermetikk', linser: 'tørrvarer og hermetikk',
  kikærter: 'tørrvarer og hermetikk', hvite: 'tørrvarer og hermetikk',
  bakepulver: 'tørrvarer og hermetikk', gjær: 'tørrvarer og hermetikk',
  natron: 'tørrvarer og hermetikk', honning: 'tørrvarer og hermetikk',
  sirup: 'tørrvarer og hermetikk', nøtter: 'tørrvarer og hermetikk',
  mandler: 'tørrvarer og hermetikk', valnøtter: 'tørrvarer og hermetikk',
  cashew: 'tørrvarer og hermetikk', peanøtter: 'tørrvarer og hermetikk',
  pistasjnøtter: 'tørrvarer og hermetikk', rosiner: 'tørrvarer og hermetikk',
  dadler: 'tørrvarer og hermetikk', tørkede: 'tørrvarer og hermetikk',
  müsli: 'tørrvarer og hermetikk', cornflakes: 'tørrvarer og hermetikk',
  granola: 'tørrvarer og hermetikk', grøt: 'tørrvarer og hermetikk',
  couscous: 'tørrvarer og hermetikk', quinoa: 'tørrvarer og hermetikk',
  byggryner: 'tørrvarer og hermetikk', linfrø: 'tørrvarer og hermetikk',
  chiafrø: 'tørrvarer og hermetikk', sesamfrø: 'tørrvarer og hermetikk',
  kakao: 'tørrvarer og hermetikk',
  sammalt: 'tørrvarer og hermetikk', mutti: 'tørrvarer og hermetikk',
  sprøstekt: 'tørrvarer og hermetikk', solsikke: 'tørrvarer og hermetikk',
  bakepapir: 'tørrvarer og hermetikk',

  // Snacks
  chips: 'snacks', popcorn: 'snacks', nachos: 'snacks', tortillachips: 'snacks',
  pringles: 'snacks', potetgull: 'snacks', riskaker: 'snacks', maissnacks: 'snacks',
  sjokolade: 'snacks', sjokoladebiter: 'snacks', marshmallows: 'snacks',
  godteri: 'snacks', lakrits: 'snacks', vingummi: 'snacks', karamell: 'snacks',
  drops: 'snacks', tyggegummi: 'snacks', skumbananer: 'snacks', gelébønner: 'snacks',
  nøttemix: 'snacks', studentmat: 'snacks', proteinbar: 'snacks',
  energibar: 'snacks', nøttebar: 'snacks', sjokoladebar: 'snacks',
  twix: 'snacks', snickers: 'snacks', kitkat: 'snacks', daim: 'snacks',
  kvikk: 'snacks', freia: 'snacks',
  smågodt: 'snacks', godtepose: 'snacks', godteposer: 'snacks',
  seigmenn: 'snacks', kinderegg: 'snacks', lomlom: 'snacks',

  // Frys
  pizza: 'frys', iskrem: 'frys', frossen: 'frys', frossenfisk: 'frys',
  frossengrønnsaker: 'frys', frosne: 'frys', frossenmat: 'frys',
  pommes: 'frys', nuggets: 'frys', fiskepinner: 'frys', fiskekaker: 'frys',
  fiskepudding: 'frys', wienerschnitzel: 'frys', lasagneplate: 'frys',
  sorbet: 'frys',
  is: 'frys', fiskegrateng: 'frys',

  // Drikke
  juice: 'drikke', appelsinjuice: 'drikke', eplejuice: 'drikke',
  vann: 'drikke', mineralvann: 'drikke', kildevann: 'drikke',
  brus: 'drikke', cola: 'drikke', fanta: 'drikke', sprite: 'drikke',
  kaffe: 'drikke', espresso: 'drikke', kaffekapsel: 'drikke',
  te: 'drikke', urtete: 'drikke', grønn: 'drikke',
  saft: 'drikke', smoothie: 'drikke', øl: 'drikke', vin: 'drikke',
  rødvin: 'drikke', hvitvin: 'drikke', musserende: 'drikke',
  sider: 'drikke', energidrikk: 'drikke', sportsdrikk: 'drikke',
  varm: 'drikke', latte: 'drikke', cappuccino: 'drikke',

  // Helse og hygiene
  sjampo: 'helse og hygiene', balsam: 'helse og hygiene', hårmaske: 'helse og hygiene',
  tannkrem: 'helse og hygiene', tannbørste: 'helse og hygiene', tanntråd: 'helse og hygiene',
  munnvann: 'helse og hygiene', såpe: 'helse og hygiene', dusjsåpe: 'helse og hygiene',
  deodorant: 'helse og hygiene', solkrem: 'helse og hygiene', aftershave: 'helse og hygiene',
  barberskum: 'helse og hygiene', barberblad: 'helse og hygiene', barberhøvel: 'helse og hygiene',
  hudkrem: 'helse og hygiene', ansiktskrem: 'helse og hygiene', bodylotion: 'helse og hygiene',
  leppepomade: 'helse og hygiene', sminke: 'helse og hygiene', foundation: 'helse og hygiene',
  nesespray: 'helse og hygiene', halstabletter: 'helse og hygiene', ibuprofen: 'helse og hygiene',
  paracetamol: 'helse og hygiene', plaster: 'helse og hygiene', bandasje: 'helse og hygiene',
  tamponger: 'helse og hygiene', bind: 'helse og hygiene', truse: 'helse og hygiene',
  kontaktlinse: 'helse og hygiene', linseveske: 'helse og hygiene',
  bomullspinner: 'helse og hygiene', bomullspads: 'helse og hygiene',
  neglelakk: 'helse og hygiene', neglelakkfjerner: 'helse og hygiene',
  parfyme: 'helse og hygiene', hårspray: 'helse og hygiene', hårgelé: 'helse og hygiene',
  vitaminer: 'helse og hygiene', kosttilskudd: 'helse og hygiene',
  tørkepapir: 'helse og hygiene', lommetørklær: 'helse og hygiene',
  bleier: 'helse og hygiene', bleie: 'helse og hygiene', buksebleier: 'helse og hygiene',
  stellematte: 'helse og hygiene', våtservietter: 'helse og hygiene',
  ammeinnlegg: 'helse og hygiene', håndsåpe: 'helse og hygiene', libero: 'helse og hygiene',

  // Renhold
  vaskemiddel: 'renhold', oppvaskmiddel: 'renhold', skyllemiddel: 'renhold',
  maskintabs: 'renhold', oppvasktabs: 'renhold', klargjøringsmiddel: 'renhold',
  rengjøringsmiddel: 'renhold', allesrenser: 'renhold', flekkmiddel: 'renhold',
  toalettpapir: 'renhold', papirhåndkle: 'renhold', kjøkkenrulle: 'renhold',
  søppelpose: 'renhold', søppelposer: 'renhold', plastpose: 'renhold',
  klut: 'renhold', kluter: 'renhold', svamp: 'renhold', skuresvamp: 'renhold',
  skurebørste: 'renhold', gulvmopp: 'renhold', støvsugerpose: 'renhold',
  håndoppvask: 'renhold', tøymykner: 'renhold', blekmiddel: 'renhold',
  desinfeksjon: 'renhold', antibac: 'renhold', fukttørkepapir: 'renhold',
  mikrofiberklut: 'renhold', strålerulle: 'renhold', vindusrens: 'renhold',
  baderomspray: 'renhold', kalkfjerner: 'renhold',
  dopapir: 'renhold', vindusspray: 'renhold', zalo: 'renhold',
}

export function guessCategory(
  itemName: string,
  categories: ShoppingCategory[]
): ShoppingCategory | null {
  const normalized = itemName.toLowerCase().trim()
  const key = Object.keys(WORD_MAP).find(
    (k) => normalized === k || normalized.startsWith(k + ' ')
  )
  if (!key) return null
  const catName = WORD_MAP[key]
  const match = categories.find((c) => c.name.toLowerCase() === catName) ?? null
  if (!match) console.warn(`[categorize] ingen kategori for "${catName}". Tilgjengelige: ${categories.map(c => c.name).join(' | ')}`)
  return match
}
